### ISSUE TITLE
what is the difference between add and inc?

### ISSUE THREAD

**Issue by Bunnycxk** [ligen131/equal_to_p#18]
![667d8d103b81a38d7b389b17536e6204](https://github.com/ligen131/ggj2024-game/assets/41613268/faa9223f-3643-40a0-9ff5-2b0ff648abfe)

**Comment by cutekibry** [comment]
Fixed by [95b5e6e](https://github.com/ligen131/equal_to_p/commit/95b5e6e2500c76a770c39fab492321f841c391ca).
